spring:
  application:
    name: service-c
  config:
    import:
      - nacos:/service_c.yaml
#      - nacos:/service_a_config.yaml?group=SERVICE_A_CONFIGS&refreshEnabled=true
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          hikari:
            connection-test-query: SELECT 1
            max-lifetime: 30000
            max-pool-size: 20
            min-idle: 5
          password: ${DB_PASSWORD:zd199578}
          url: jdbc:mysql://${MYSQL_HOST:192.168.5.66}:${MYSQL_PORT:33106}/test?serverTimezone=Asia/Shanghai&autoReconnect=true&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
          username: ${DB_USERNAME:root}
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_DISCOVERY_ADDR:192.168.5.66:8848}
        heart-beat-interval: 1000
        namespace: ${NACOS_DISCOVERY_NAME_SPACE:c8fd8e42-04fb-4c57-bc46-18ddad72b408}
        group: ${NACOS_DISCOVERY_GROUP:DEFAULT_GROUP}
        ephemeral: ${EPHEMERAL:true}
        service: ${spring.application.name}
#        metadata:
#          preserved.heart.beat.interval: 1
#          preserved.heart.beat.timeout: 3
#          preserved.ip.delete.timeout: 3
        heart-beat-timeout: 3000
        ip-delete-timeout: 3000
      config:
        server-addr: ${NACOS_CONFIG_ADDR:192.168.5.66:8848}
        file-extension: yaml
        enabled: true #false:会根据spring.profiles.active读取本地文件
        namespace: ${NACOS_CONFIG_NAME_SPACE:c8fd8e42-04fb-4c57-bc46-18ddad72b408}
        refresh-enabled: true


logging:
  config: classpath:${LOGBACK_FILE:logback-local.xml}
  level:
    com.alibaba.nacos: debug
feign:
  okhttp:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 60000
      dc:
        connectTimeout: 10000
        readTimeout: 10000

# -----------seata--------------
seata:
  data-source-proxy-mode: AT
  tx-service-group: default_tx_group
  enabled: true
  config:
    type: nacos
    nacos:
      server-addr: 192.168.5.66:8848
      group: SEATA_GROUP
      namespace: 4f3764ed-4f7d-4891-91a2-dcedc704b0e4
      data-id: seataServer.properties
  registry:
    type: nacos
    nacos:
      server-addr: 192.168.5.66:8848
      group: SEATA_GROUP
      namespace: 4f3764ed-4f7d-4891-91a2-dcedc704b0e4
      cluster: default
      application: seata-server
  service:
    vgroup-mapping:
      default_tx_group: default
    grouplist:
      default: 192.168.5.66:8091
    disable-global-transaction: false